package com.jit.imhi.model;

import java.util.Date;

public class Friend {
    public Friend(){}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Friend.user_id
     *
     * @mbggenerated Sat Jan 13 10:14:02 CST 2018
     */
    public Friend(Integer userId,Integer friendId,Date date){
        this.userId = userId;
        this.friendId = friendId;
        this.addDate = date;
    }
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Friend.friend_id
     *
     * @mbggenerated Sat Jan 13 10:14:02 CST 2018
     */
    private Integer friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Friend.add_date
     *
     * @mbggenerated Sat Jan 13 10:14:02 CST 2018
     */
    private Date addDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Friend.user_id
     *
     * @return the value of Friend.user_id
     * @mbggenerated Sat Jan 13 10:14:02 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Friend.user_id
     *
     * @param userId the value for Friend.user_id
     * @mbggenerated Sat Jan 13 10:14:02 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Friend.friend_id
     *
     * @return the value of Friend.friend_id
     * @mbggenerated Sat Jan 13 10:14:02 CST 2018
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Friend.friend_id
     *
     * @param friendId the value for Friend.friend_id
     * @mbggenerated Sat Jan 13 10:14:02 CST 2018
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Friend.add_date
     *
     * @return the value of Friend.add_date
     * @mbggenerated Sat Jan 13 10:14:02 CST 2018
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Friend.add_date
     *
     * @param addDate the value for Friend.add_date
     * @mbggenerated Sat Jan 13 10:14:02 CST 2018
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
}