package com.jit.imhi.model;

public class Groupuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GroupUser.member_id
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GroupUser.group_id
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GroupUser.group_membership
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    private String groupMembership;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GroupUser.member_id
     *
     * @return the value of GroupUser.member_id
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GroupUser.member_id
     *
     * @param memberId the value for GroupUser.member_id
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GroupUser.group_id
     *
     * @return the value of GroupUser.group_id
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GroupUser.group_id
     *
     * @param groupId the value for GroupUser.group_id
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GroupUser.group_membership
     *
     * @return the value of GroupUser.group_membership
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    public String getGroupMembership() {
        return groupMembership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GroupUser.group_membership
     *
     * @param groupMembership the value for GroupUser.group_membership
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    public void setGroupMembership(String groupMembership) {
        this.groupMembership = groupMembership == null ? null : groupMembership.trim();
    }
}