package com.jit.imhi.model;

import java.util.Date;

public class Groupchat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GroupChat.group_id
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GroupChat.user_id
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GroupChat.group_name
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GroupChat.create_date
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GroupChat.head_url
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    private String headUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GroupChat.group_id
     *
     * @return the value of GroupChat.group_id
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GroupChat.group_id
     *
     * @param groupId the value for GroupChat.group_id
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GroupChat.user_id
     *
     * @return the value of GroupChat.user_id
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GroupChat.user_id
     *
     * @param userId the value for GroupChat.user_id
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GroupChat.group_name
     *
     * @return the value of GroupChat.group_name
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GroupChat.group_name
     *
     * @param groupName the value for GroupChat.group_name
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GroupChat.create_date
     *
     * @return the value of GroupChat.create_date
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GroupChat.create_date
     *
     * @param createDate the value for GroupChat.create_date
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GroupChat.head_url
     *
     * @return the value of GroupChat.head_url
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GroupChat.head_url
     *
     * @param headUrl the value for GroupChat.head_url
     *
     * @mbggenerated Thu Jan 18 01:37:05 CST 2018
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }
}