package com.jit.imhi.model;

import java.util.Date;

public class Logininfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginInfo.login_id
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    private Integer loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginInfo.user_id
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginInfo.ip_addr
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    private String ipAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginInfo.ip_port
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    private String ipPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginInfo.login_date
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    private Date loginDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginInfo.login_id
     *
     * @return the value of LoginInfo.login_id
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginInfo.login_id
     *
     * @param loginId the value for LoginInfo.login_id
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginInfo.user_id
     *
     * @return the value of LoginInfo.user_id
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginInfo.user_id
     *
     * @param userId the value for LoginInfo.user_id
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginInfo.ip_addr
     *
     * @return the value of LoginInfo.ip_addr
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginInfo.ip_addr
     *
     * @param ipAddr the value for LoginInfo.ip_addr
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginInfo.ip_port
     *
     * @return the value of LoginInfo.ip_port
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    public String getIpPort() {
        return ipPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginInfo.ip_port
     *
     * @param ipPort the value for LoginInfo.ip_port
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    public void setIpPort(String ipPort) {
        this.ipPort = ipPort == null ? null : ipPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginInfo.login_date
     *
     * @return the value of LoginInfo.login_date
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    public Date getLoginDate() {
        return loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginInfo.login_date
     *
     * @param loginDate the value for LoginInfo.login_date
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }
}