package com.jit.imhi.model;

public class Numinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NumInfo.user_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NumInfo.friend_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    private Integer friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NumInfo.friend_type
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    private String friendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NumInfo.new_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    private Integer newId = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NumInfo.old_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
        private Integer oldId = 0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NumInfo.user_id
     *
     * @return the value of NumInfo.user_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NumInfo.user_id
     *
     * @param userId the value for NumInfo.user_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NumInfo.friend_id
     *
     * @return the value of NumInfo.friend_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NumInfo.friend_id
     *
     * @param friendId the value for NumInfo.friend_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NumInfo.friend_type
     *
     * @return the value of NumInfo.friend_type
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    public String getFriendType() {
        return friendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NumInfo.friend_type
     *
     * @param friendType the value for NumInfo.friend_type
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    public void setFriendType(String friendType) {
        this.friendType = friendType == null ? null : friendType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NumInfo.new_id
     *
     * @return the value of NumInfo.new_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    public Integer getNewId() {
        return newId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NumInfo.new_id
     *
     * @param newId the value for NumInfo.new_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    public void setNewId(Integer newId) {
        this.newId = newId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NumInfo.old_id
     *
     * @return the value of NumInfo.old_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    public Integer getOldId() {
        return oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NumInfo.old_id
     *
     * @param oldId the value for NumInfo.old_id
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    public void setOldId(Integer oldId) {
        this.oldId = oldId;
    }
}