package com.jit.imhi.model;

import java.util.Date;

public class OfflineMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.messag_id
     *
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    private Integer messagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.to_id
     *
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    private Integer toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.from_user_id
     *
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    private Integer fromUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.text_type
     *
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    private String textType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.text_content
     *
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    private String textContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.message_type
     *
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    private String messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.date
     *
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.messag_id
     *
     * @return the value of offline_message.messag_id
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public Integer getMessagId() {
        return messagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_message.messag_id
     *
     * @param messagId the value for offline_message.messag_id
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public void setMessagId(Integer messagId) {
        this.messagId = messagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.to_id
     *
     * @return the value of offline_message.to_id
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_message.to_id
     *
     * @param toId the value for offline_message.to_id
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.from_user_id
     *
     * @return the value of offline_message.from_user_id
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public Integer getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_message.from_user_id
     *
     * @param fromUserId the value for offline_message.from_user_id
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.text_type
     *
     * @return the value of offline_message.text_type
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public String getTextType() {
        return textType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_message.text_type
     *
     * @param textType the value for offline_message.text_type
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public void setTextType(String textType) {
        this.textType = textType == null ? null : textType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.text_content
     *
     * @return the value of offline_message.text_content
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public String getTextContent() {
        return textContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_message.text_content
     *
     * @param textContent the value for offline_message.text_content
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public void setTextContent(String textContent) {
        this.textContent = textContent == null ? null : textContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.message_type
     *
     * @return the value of offline_message.message_type
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_message.message_type
     *
     * @param messageType the value for offline_message.message_type
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType == null ? null : messageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.date
     *
     * @return the value of offline_message.date
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_message.date
     *
     * @param date the value for offline_message.date
     * @mbggenerated Sun Jan 14 18:53:58 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }
}