spring:
  datasource:
    url: jdbc:mysql://120.77.155.191:3306/imHi?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: imdb
    password: imdb
debug: true
mybatis:
  type-aliases-package: com.example.demo.model
  config-location: classpath:mybaties.xml