package com.jit.imhi.mapper;

import com.jit.imhi.model.Groupchat;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GroupchatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GroupChat
     *
     * @mbggenerated Thu Jan 18 17:14:55 CST 2018
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GroupChat
     *
     * @mbggenerated Thu Jan 18 17:14:55 CST 2018
     */
    int insert(Groupchat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GroupChat
     *
     * @mbggenerated Thu Jan 18 17:14:55 CST 2018
     */
    Groupchat selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GroupChat
     *
     * @mbggenerated Thu Jan 18 17:14:55 CST 2018
     */
    List<Groupchat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GroupChat
     *
     * @mbggenerated Thu Jan 18 17:14:55 CST 2018
     */
    int updateByPrimaryKey(Groupchat record);

    /* yuyisummer selectOwner*/
    int selectOwner(@Param("group_id")int group_id);
    /*liuyunxing*/
    List<Groupchat> selectByGroupName(@Param("group_name") String groupName);
    /*yuyisummer select all owner*/
    List<String>  selectAllOwn(@Param("userId")Integer user_id);
}