package com.jit.imhi.mapper;

import com.jit.imhi.model.Groupchat;
import com.jit.imhi.model.Groupuser;
import com.jit.imhi.model.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GroupuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GroupUser
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    int deleteByPrimaryKey(@Param("memberId") Integer memberId, @Param("groupId") Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GroupUser
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    int insert(Groupuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GroupUser
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    Groupuser selectByPrimaryKey(@Param("memberId") Integer memberId, @Param("groupId") Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GroupUser
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    List<Groupuser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GroupUser
     *
     * @mbggenerated Tue Jan 16 19:16:40 CST 2018
     */
    int updateByPrimaryKey(Groupuser record);

    /* yuyisummer 1.18 20.08 搜索群包括此人ID*/
    List<Groupchat>  selectByUserID(@Param("memberId") Integer memberId);
    /*yuyisummer 1.27 23.37 搜索群包括此人ID，用来查数数量的*/
    List<String>  selectByUserIdNum(@Param("memberId") Integer memberId);


    List<User> selectUsers(@Param("groupId") Integer groupId);
}