package com.jit.imhi.mapper;

import com.jit.imhi.model.HistoryMessage;
import java.util.List;

public interface HistoryMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_message
     *
     * @mbggenerated Wed Jan 17 11:08:47 CST 2018
     */
    int deleteByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_message
     *
     * @mbggenerated Wed Jan 17 11:08:47 CST 2018
     */
    int insert(HistoryMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_message
     *
     * @mbggenerated Wed Jan 17 11:08:47 CST 2018
     */
    HistoryMessage selectByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_message
     *
     * @mbggenerated Wed Jan 17 11:08:47 CST 2018
     */
    List<HistoryMessage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_message
     *
     * @mbggenerated Wed Jan 17 11:08:47 CST 2018
     */
    int updateByPrimaryKey(HistoryMessage record);
}