package com.jit.imhi.mapper;

import com.jit.imhi.model.HistoryMessage;
import com.jit.imhi.model.Numinfo;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface HistoryMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_message
     *
     * @mbggenerated Mon Jan 15 14:38:26 CST 2018
     */

    int deleteByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_message
     *
     * @mbggenerated Mon Jan 15 14:38:26 CST 2018
     */

    int insert(HistoryMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_message
     *
     * @mbggenerated Mon Jan 15 14:38:26 CST 2018
     */

    HistoryMessage selectByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_message
     *
     * @mbggenerated Mon Jan 15 14:38:26 CST 2018
     */

    List<HistoryMessage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_message
     *
     * @mbggenerated Mon Jan 15 14:38:26 CST 2018
     */

    int updateByPrimaryKey(HistoryMessage record);

    //yuyisummer 1.20 0.15
  /*  int updateAddSuccess(@Param("userFromId") Integer userFromId,
                         @Param("toId") Integer toId, @Param("messageType")
                                 Integer messageType);
*/
    int updateType(HistoryMessage record);

    /*yuyisummer  List<HistoryMessage> selectTheNotice(); */
/*yuyisummer 1.21 0.09 selectTheNum*/
    int selectTheNum(Numinfo numinfo);

    int selectNoticNum(Numinfo numinfo);

    List<HistoryMessage> selectNotic(Numinfo numinfo);

    int updateGroupType(HistoryMessage record);
}