package com.jit.imhi.mapper;

import com.jit.imhi.model.Logininfo;
import java.util.List;

public interface LogininfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginInfo
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginInfo
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    int insert(Logininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginInfo
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    Logininfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginInfo
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    List<Logininfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginInfo
     *
     * @mbggenerated Fri Jan 12 21:12:57 CST 2018
     */
    int updateByPrimaryKey(Logininfo record);
}