package com.jit.imhi.mapper;

import com.jit.imhi.model.Numinfo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NuminfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NumInfo
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("friendId") Integer friendId, @Param("friendType") String friendType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NumInfo
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    int insert(Numinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NumInfo
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    Numinfo selectByPrimaryKey(@Param("userId") Integer userId, @Param("friendId") Integer friendId, @Param("friendType") String friendType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NumInfo
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    List<Numinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NumInfo
     *
     * @mbggenerated Thu Jan 18 17:22:04 CST 2018
     */
    int updateByPrimaryKey(Numinfo record);

    //yuyisummer 1.18 20.23
    Numinfo selectAllBy(@Param("userId") Integer userId, @Param("friendId") Integer friendId,@Param("friendType") String friendType);

    //yuyisummer 1.19 20.25
    List<String> selectForMap();

    //yuyisummer 1.19 22.04
    int updateNoneOld(Numinfo record);

    //yuyisummer 1.20 23.28
    String selectNumOne(Numinfo record);

    String selectNumTwo(Numinfo record);
}